### ISSUE TITLE
Collisions is not a constructor

### ISSUE THREAD

**Issue by IceHacks** [Prozi/detect-collisions#1]
My code is simply
```
var Collisions = require("detect-collisions");

var system = new Collisions();
var result = system.createResult();
```
but I get the error `TypeError: Collisions is not a constructor`. I know what that means but `Collisions` is supposed to be a constructor. Also when trying it without the `new` it says `Collisions is not a function`. I probably made an obvious mistake but I can't find it.

**Edit**
When `console.log`ing `Collisions` everything looks defined and `default` is a function.

**Edit #2**
```
var Collisions = require("detect-collisions").default;

var system = new Collisions();
var result = system.createResult();
```
Adding `.default` works for some reason.

**Comment by zhuravlenko2555dev** [comment]
thanks for help

**Comment by Prozi** [comment]
Sorry there was error in the documentation :(

Please use like:

```
const {Collisions} = require('detect-collisions');

const system = new Collisions();
```

Please update to version `2.4.3` the docs are up to date now

**Comment by Prozi** [comment]
```
// other options:
const Collisions = require('detect-collisions').default;
import Collisions from 'detect-collisions';
```

**Comment by Prozi** [comment]
this is because there is more to the engine than just Collisions, there are

```
Circle: function()
Collisions: function()
Point: function()
Polygon: function()
Result: function()
default: function() // equal to Collisions
```

**Comment by IceHacks** [comment]
Thank you. If I only watched my email I would've seen this before giving up xD. My projects are gone now anyways (I had a PC problem)
