### ISSUE TITLE
How to calculate the parameters of the Polygon?

### ISSUE THREAD

**Issue by StringKe** [Prozi/detect-collisions#12]
Multiple polygons start with the upper left corner (0,0) and then express themselves in terms of width and height, and are rendered around the center point. How to create such a polygon?

![image](https://user-images.githubusercontent.com/31089228/132181449-5d72a5ef-4ad4-405c-b507-205a6a5bc7e4.png)

```
new Polygon(x, y, [
		// left top
		[0, 0],
		// left bottom
		[0, h],
		// right bottom
		[w, h],
		// right top
		[w, 0],
]);
```

// rotate unit is deg
example data: {x:40,y:50,w:100,h:150,rotate:30}

English is not my native language; please excuse typing errors.

**Comment by Prozi** [comment]
you can do this with or without rotation

as far as i know less rotations = less computations = faster collisions system

```
const createPolygon = (x, y, w, h, deg) => {
  const rad = Math.PI / 180 * deg;

  return new Polygon(x, y, [0, 0], [0, h], [w, h], [w, 0], rad)
}
```

or

```
const createPolygon = (x, y, w, h, deg) => {
  return new Polygon(x, y, [0, -h/2], [w/2, 0], [0, h/2], [-w/2, 0])
}
```

**Comment by StringKe** [comment]
ok, thanks.
