### ISSUE TITLE
Is it possible to add aabox data to calculate multiple polygons?

### ISSUE THREAD

**Issue by StringKe** [Prozi/detect-collisions#13]
I was looking at the source code and found that there is aabb data for calculating a single and detected element. Can I provide aabb data for calculating certain polygons?

Used to calculate the bounding box of multiple polygons
```typescript
	/**
	 * get elements bounding box
	 * @param ids element uuid
	 */
	getBoundingBox(ids: string[]) {
		const polygons: Polygon[] = ids.map(id => this.elements.get(id));
		polygons.map(polygon => {
			// do somethings
		});
	}

```

English is not my native language; please excuse typing errors.

**Comment by StringKe** [comment]
Maybe the typescript definition should expose bvh related attributes to the outside world?

**Comment by Prozi** [comment]
> Maybe the typescript definition should expose bvh related attributes to the outside world?

I will try to do that in some automatic way in the meantime see

https://github.com/Prozi/detect-collisions/blob/master/source/modules/BVH.js

also try

```
$ node

const circle = new (require("detect-collisions").Circle)(0, 0, 100);

console.log(circle._points)
```

this is an array of [x,y,x,y,x,y,x,y,...]

you propably want to find minx and miny maxx and maxy yourself

I have no idea why you need that :)

**Comment by Prozi** [comment]
@StringKe

**Comment by StringKe** [comment]
@Prozi 
I just saw that the `_bvh` parameter corresponds to the bounding box. I want to avoid calculating it again in other places and save CPU calculations.

**Comment by Prozi** [comment]
after version 3 this is done in body.updateAABB()

**Comment by Prozi** [comment]
but actually you should do 

```
system.updateBody(body);
```

which removes body from rbush, updates aabb, then inserts it back

**Comment by Prozi** [comment]
but to answer you original question:

```
Can I provide aabb data for calculating certain polygons?

Used to calculate the bounding box of multiple polygons
```

@StringKe I think that is not possible, each polygon has its own separate aabb :(

closing the issue and feel free to reopen if you have more comments, or if I misunderstood somethin
