### ISSUE TITLE
How to efficiently detect collisions on a batch of objects

### ISSUE THREAD

**Issue by hpx7** [Prozi/detect-collisions#14]
I currently am using the library in the following way:
https://github.com/hpx7/ship-battle/blob/b9ac63b6b0a2e3f55e813d0154a693b1a5eb66f5/server/impl.ts#L86-L94

Inline version:
```ts
    state.ships.forEach((ship) => {
      state.cannonBalls.forEach((cannonBall, idx) => {
        if (ship.player !== cannonBall.firedBy && ship.body.collides(cannonBall.body)) {
          ship.handleCollision();
          state.cannonBalls.splice(idx, 1);
          cannonBall.body.remove();
        }
      });
    });
```

Is there a more efficient way to detect all collisions between ships and cannonBalls rather than using this quadratic complexity loop?

**Comment by Prozi** [comment]
system.checkAll(handleCollisions)

**Comment by Prozi** [comment]
@hpx7 

```
system.checkAll(handleCollisions)
```

will check AABB (BVH) then if the boxes overlap checks the SAT colliders for real collisions

you can also try something like

```
    state.ships.forEach((ship) => {
      system.checkAll((ship, response) => {
        const cannonBall = response.b;

        if (ship.player !== cannonBall.firedBy) {
          ship.handleCollision();
          state.cannonBalls.splice(idx, 1);
          cannonBall.body.remove();
        }
      });
    });
```

as checkAll follows the same principle but only checks one object

closing the issue and feel free to reopen if you have more comments, or if I misunderstood something

**Comment by hpx7** [comment]
@Prozi I finally got the chance to upgrade to the latest version. You can see the diff here if you're curious: https://github.com/hathora/ship-battle/commit/64952831334e404d2bc054918696df29e38991f6

How do you suggest I figure out which colliding body represents which object in my game (ship or cannonBall)?

```ts
    state.system.checkAll((response) => {
      console.log("response.a", response.a); // this is a Polygon (ship)
      console.log("response.b", response.b); // this is a Circle (cannonBall)
      // but I don't have references to ship and cannonBall
      // how can I check if (ship.player !== cannonBall.firedBy)?
    });
```

**Comment by Prozi** [comment]
const { System } = require("detect-collisions");
const physics = new System();

const cannonBall = { name: "ball" }; // create your ball
cannonBall.body = physics.createCircle({ x: 0, y: 0 }, 10);
cannonBall.body.gameObject = cannonBall;

const ship = { name: "ship" }; // create your ship
ship.body = physics.createPolygon({ x: 0, y: 0 }, [{ x: 0, y: 0 }, { x: 10,
y: 0 }]);
ship.body.gameObject = ship;

physics.checkAll((response) => {
    console.log("response.a", response.a.gameObject); // this is a Polygon
(ship)
    console.log("response.b", response.b.gameObject); // this is a Circle
(cannonBall)
});

// remember to clear references to gameObject when destroying:
cannonBall.body.gameObject = null;
// before removing:
physics.remove(cannonBall);
