### ISSUE TITLE
No pos property since 3.0.2

### ISSUE THREAD

**Issue by Pii2** [Prozi/detect-collisions#16]
Hi,
I have updated to the latest version.
According to the doku I can update a polygon with pos.x. 

But my IDE tells me that this property is not present.
![image](https://user-images.githubusercontent.com/9112639/141521796-b3778264-1252-4cf9-bce5-c06f5a230c5f.png)

**Comment by Prozi** [comment]
hello

please use latest version, specify what version you are using

the pos is not missing

maybe the typedefs are wrong on your end

i am using this in demos and it works

if nothing else works cast hitbox to any

regards

pt., 12 lis 2021, 20:09 użytkownik Pii ***@***.***> napisał:

**Comment by Prozi** [comment]
also how do you define hitbox and how do you import library

sob., 13 lis 2021, 11:06 użytkownik Jacek Jan Pietal ***@***.***>
napisał:

**Comment by Pii2** [comment]
Hi,

I have tried with the latest version 3.0.7.

I import it like this:

`import {Polygon, System} from 'detect-collisions';`

These are my only options:

![image](https://user-images.githubusercontent.com/9112639/141645992-9b19cbdb-eaeb-48cc-b8ef-2936d722add8.png)

regards

**Comment by Prozi** [comment]
if you can provide a minimal repo with reproduction i will try to help,
regards

sob., 13 lis 2021, 14:41 użytkownik Pii ***@***.***> napisał:

**Comment by Prozi** [comment]
you can also try to install `@types/sat` and see if that helps

**Comment by Pii2** [comment]
Hi thanks for the replay!

I was able to solve the Problem by adding the following line to my `tsconfig.json`

`"allowSyntheticDefaultImports": true,`

Thanks anyway and by the way, great library!

**Comment by Prozi** [comment]
i am happy you got it working!

regards

niedz., 14 lis 2021, 14:02 użytkownik Pii ***@***.***>
napisał:
