### ISSUE TITLE
Property 'pos' does not exist on type 'Polygon'

### ISSUE THREAD

**Issue by hpx7** [Prozi/detect-collisions#17]
On the latest version typescript complains when i try and update the position of a polygon

**Comment by Pii2** [comment]
#16 :)

**Comment by hpx7** [comment]
Cool, for me adding
```
    "@types/rbush": "^3.0.0",
    "@types/sat": "^0.0.31",
```
as devDependencies fixed it.

I think these should be in `dependencies` in this package instead of `devDependencies` so that this works out of the box for users.

For additional discussion on this topic see https://www.reddit.com/r/typescript/comments/byar8w/tool_to_tell_me_which_types_deps_should_be_deps/

**Comment by Prozi** [comment]
@hpx7 @Pii2 

I have moved the types above-mentioned by hpx7 in the dependencies since version 3.1.0

can you try that and see if it's better and doesnt require workarounds anymore?

thank you.

**Comment by Pii2** [comment]
Hey, yes now it works out of the box, good work :)

**Comment by Prozi** [comment]
thanks :) closing then
