### ISSUE TITLE
collides definition is wrong

### ISSUE THREAD

**Issue by artpumpkin** [Prozi/detect-collisions#18]
Hello, I just want to report a weird issue, after upgrading to the latest version, this is not working as expected from the documentation.

![image](https://user-images.githubusercontent.com/46715750/144694095-dd3528b9-a882-4e44-85b3-ebc1e9e4c197.png)

The documentation says that this function takes 2 arguments to test the possible collision between them, not sure how to do it.

![image](https://user-images.githubusercontent.com/46715750/144694118-778b4fd2-7bd2-496d-a831-735a241989dc.png)

When I try to test it out, it says it only takes 1 argument.
![image](https://user-images.githubusercontent.com/46715750/144694162-a6a7298b-d9ef-4471-a5f6-fd6648095255.png)

**Comment by Prozi** [comment]
hello

i renamed it without updating the docs

it should be checkCollision

https://github.com/Prozi/detect-collisions/blob/a57d0ced082a8798dfd3c0cf34114b231a0e9dd7/src/system.ts#L136

will fix docs in upcoming days

thanks


sob., 4 gru 2021, 03:46 użytkownik Salah Eddine Lachkar <
***@***.***> napisał:

**Comment by artpumpkin** [comment]
No worries, thanks man!

**Comment by Prozi** [comment]
updated docs thanks
