### ISSUE TITLE
how to update point position?

### ISSUE THREAD

**Issue by StringKe** [Prozi/detect-collisions#19]
old version:
`point.x = newX; point.y =newY`

now version:

point is SAT.polygon how to update it?

**Comment by Prozi** [comment]
updated documentation since 3.2.0 you can use

```
point.setPosition(x, y);

// or

point.pos.x = x;
point.pos.y = y;
system.updateBody(point);
```

**Comment by Prozi** [comment]
more info here @StringKe 

https://prozi.github.io/detect-collisions/classes/Point.html#pos
