### ISSUE TITLE
Is there any unique identifier for the body after inserting to Collisions?

### ISSUE THREAD

**Issue by chanduthedev** [Prozi/detect-collisions#2]
Hi @Prozi ,

Thank you for the nice tool. I am facing some issue while inserting and deleting circle to the Collisions.  Below is my requirement. Please help me.

I will keep on adding my location details to Collisions list  and after some time I want to delete particular location from the Collisions list. Whenever adding location to the list, there is a timeout for that location, whenever that times out, I need to remove that location from the list. To do that, I need unique identifier, so that removal will be simple and efficient. 

My point here is  if I create a circle using below code, is there any unique value to identify?

`const circle  = new Circle(100, 100, 10);`

Please let me know if you need more info on this.

Thanks again.

**Comment by Prozi** [comment]
Quoting the Manual ;)

```
To use them, require the desired body class, call its constructor, and insert it into the collision system using insert().

const {Collisions, Circle, Polygon, Point} = require('detect-collisions');
 
const system = new Collisions();
 
const circle  = new Circle(100, 100, 10);
const polygon = new Polygon(50, 50, [[0, 0], [20, 20], [-10, 10]]);
const line    = new Polygon(200, 5, [[-30, 0], [10, 20]]);
const point   = new Point(10, 10);
 
system.insert(circle)
system.insert(polygon, line, point);
Collision systems expose several convenience functions for creating bodies and inserting them into the system in one step. This also avoids having to require the different body classes.

const {Collisions} = require('detect-collisions');
 
const system = new Collisions();
 
const circle  = system.createCircle(100, 100, 10);
const polygon = system.createPolygon(50, 50, [[0, 0], [20, 20], [-10, 10]]);
const line    = system.createPolygon(200, 5, [[-30, 0], [10, 20]]);
const point   = system.createPoint(10, 10);
```

so there are 2 ways of creation ok

and there are 2 ways of removing from world:

```
system.remove(polygon, point);
circle.remove();
```

check out here more info https://www.npmjs.com/package/detect-collisions#anchor-step-2

does this solve your question problem @chanduthedev ?

**Comment by chanduthedev** [comment]
Hi @Prozi,

Thanks for the quick reply. Not exactly, but I got the clue from your answer. My problem is I want to remove found potential list from the Collisions system. I think I can iterate potential list and remove one by one from Collisions system. I will try this and update if I face any issue.

Thanks again for the quick response.

**Comment by chanduthedev** [comment]
Hi @Prozi,
Its working fine. Thanks for your inputs.
Thanks again!!!.

**Comment by Prozi** [comment]
I'm glad no problem closing the issue then
