### ISSUE TITLE
Get Potentials for a subset of bodies

### ISSUE THREAD

**Issue by objectiveSee** [Prozi/detect-collisions#22]
Hello, I am building a game that has multiple users (User bodies) and multiple walls (Wall bodies). The walls don't move, but the users do. The collision logic needs to be:

- User can collide with walls
- Uses **do not** collide with other Users
- Walls will never overlap other Walls (and they have static positions)

currently I am using `getPotentials` each time a user moves and then filtering out any User bodies from the the list before checking for collision. This seems like an incorrect use of your library though. Is there a way for the BVH system to only search through Walls and not Users?  Can you recommend the best way to use your library in this scenario?

One solution is to not insert `Users` to the system, and instead only pass them as parameters into `getPotentials` and `checkCollision`. This seems a little weird as the system only contains walls. Perhaps there's a way of marking users as "not collidable" when checking for potentials. ¯\_(ツ)_/¯ 

Appreciate the help!

Snippet of code. The use of `intersection` is our hack solution to not colliding with other users.
```
    const userBox = this.getUserBox(user);

    const newPosition = topLeftUser(user);
    userBox.setPosition(newPosition.x, newPosition.y);

    // Get list of possible collision objects first as an optimization
    // (https://en.wikipedia.org/wiki/Bounding_volume_hierarchy)
    const potentials = this.system.getPotentials(userBox);

    // Filter out user boxes from collision calculation
    const potentialWalls = intersection(potentials, Object.values(this.walls));

    // Find bounding wall if present
    const boundingwall = potentialWalls.find((collider) => {
      this.system.checkCollision(userBox, collider);
      return this.system.response.aInB; // Avatar is fully inside wall
    });
```

**Comment by Prozi** [comment]
Hello

I would approach this like that:

walls have isStatic = true
https://prozi.github.io/detect-collisions/interfaces/ICollider.html#isStatic

in your game loop do

https://prozi.github.io/detect-collisions/classes/System.html#checkAll
physics.checkAll((response) => {
  if (bodyA.isStatic && !bodyB.isStatic) {
    // bodyA is wall then and bodyB is user
    handleCollision(response.a, response.b, response.overlapV);
  } else {
    // bodyA is user then and bodyB is wall
    handleCollision(response.b, response.a, response.overlapV);
  }
});

function handleCollision(wall, user, overlapV) {
  // https://prozi.github.io/detect-collisions/#6-negating-overlap
  user.setPosition(user.x - overlapV.x, user.y - overlapV.y);
}

not tested but it should work with some tweaking

Have fun with the library!

Regards, Jacek


śr., 16 mar 2022 o 18:14 Danny Ricciotti ***@***.***>
napisał(a):

**Comment by Prozi** [comment]
I read what I wrote, It should at least be

physics.checkAll((response) => {
  if (bodyA.isStatic && !bodyB.isStatic) {
    // bodyA is wall then and bodyB is user
    handleCollision(response.a, response.b, response.overlapV);
  }

  if (!bodyA.isStatic && bodyB.isStatic) {
    // bodyA is user then and bodyB is wall
    handleCollision(response.b, response.a, response.overlapV);
  }
});

śr., 16 mar 2022 o 21:51 Jacek Jan Pietal ***@***.***> napisał(a):

**Comment by objectiveSee** [comment]
Thank you @Prozi ! I will test out what you suggested and let you know how it goes. Love working with this library so far. 🚀
