### ISSUE TITLE
documentation missing #anchor-lines

### ISSUE THREAD

**Issue by objectiveSee** [Prozi/detect-collisions#23]
Minor bug: There are URLs in the README which reference `https://github.com/Prozi/detect-collisions#anchor-lines` however the `#anchor-lines` ref does not go anywhere. Should it point to #lines or should there be a different link to an #anchor-lines section?

Example: See URLs for `Lines` in this section: https://github.com/Prozi/detect-collisions#concave-polygons

**Comment by Prozi** [comment]
@objectiveSee thank you :)

I've fixed this now, it was supposed to point just a bit up, to lines.

what it means is polygons are hollow, they are like a skeleton, if there is another object inside, you have to handle that yourself. how to push away objects from themselves is up to a physics system and application using this library. as the use will differ from case to case (will it bounce? based on what? will it just stick and move away, proportionally? etc)
