### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by amir-arad** [Prozi/detect-collisions#25]
Hi
I've encountered a scenario in which I get a false positive collision between two circles:

first is `{"x":13.3338,"y":0} radius: 50` and second is `{"x":-86.6663,"y":0} radius: 50`

**Comment by Prozi** [comment]
hello @amir-arad 

how did you check?

i did

```
const { System } = require("detect-collisions")

const s = new System();
s.createCircle({"x":13.3338,"y":0}, 50);
s.createCircle({"x":-86.6663,"y":0}, 50);
s.update()
s.checkAll(console.log)
```

and no results

**Comment by amir-arad** [comment]
I found it with some property-based tests in my project as part of a larger scenario. must be something in my end. sorry for the false alarm
