### ISSUE TITLE
Why doesn't Polygon have a "center" method?

### ISSUE THREAD

**Issue by naomei** [Prozi/detect-collisions#28]
Shouldn't there be a "center" method for Polygon as well as Box?
At least I need it for my project...

```ts
// For example, it looks like this
const centerdPolygon = (polygon: Polygon) => {
  const {x,y} = polygon.getCentroid();
  polygon.translate(-x, -y);

  const pos = polygon.pos;
  polygon.setPosition(pos.x + x, pos.y + y);
};
```

**Comment by naomei** [comment]
@Prozi 

Thank you for the detailed answer.

> the center() method on box is required only because when you create a box its anchor/pivot is in top left of its corners

Yes.

> this is not the case with polygons as their anchor/pivor is in the middle

This could not be reproduced.
When I tried it, it seems that the anchor is on the upper left like Box.

I made a demo with code-sandbox below, but am I making a mistake?

https://qk3heg.csb.app/

**Comment by Prozi** [comment]
@naomei I saw the demo and it seems you might be right.

I will try to provide some tests and implement center for polygons too if I will confirm this myself in next days

thanks for pointing this out

**Comment by Prozi** [comment]
@naomei 

you are totally right!

please see

https://github.com/Prozi/detect-collisions/releases/tag/v6.0.0

and please use v6.0.0+

please close issue if you think all is good now

**Comment by Prozi** [comment]
here are the relevant changes in case you might find some errors in my code

https://github.com/Prozi/detect-collisions/commit/113120ed4d846faf91ed332e921fa07dec6abf40

**Comment by Prozi** [comment]
actually v6.0.1 as v6.0.0 had not working drawBVH

**Comment by naomei** [comment]
@Prozi 

Thank you for the fix.
I've checked with version `6.0.2` and I think it's working perfectly!
