### ISSUE TITLE
createCircle has no BodyOptions parameter?

### ISSUE THREAD

**Issue by JasonAppx** [Prozi/detect-collisions#29]
I noticed that system.createCircle has no BodyOptions parameter. Is it intended? For now I'll have to set isStatic and isTrigger after the creation?

**Comment by Prozi** [comment]
@JasonAppx please try in v6.2.0 it's fixed now

also added tests for each other body type to test `create*` `options` parameter and found that point was missing options too so I fixed that too. thank you!

**Comment by Prozi** [comment]
closing as fixed
