### ISSUE TITLE
is it possible to remove the dependencies?

### ISSUE THREAD

**Issue by amir-arad** [Prozi/detect-collisions#3]
I'm trying to minimize the size of my app and i see that you're not using any libraries but you're declaring some tools in package.json dependencies

**Comment by Prozi** [comment]
Closed by https://github.com/Prozi/detect-collisions/commit/dbdb45dab5c0eda55367ec9aff7ec105f137be70

THANK YOU FOR YOUR HELP but I extended that a bit

**Comment by Prozi** [comment]
Enjoy version 2.4.4 on npm

**Comment by Prozi** [comment]
cc @amir-arad
