### ISSUE TITLE
Best practices on modifying Bodies for collision masks with Typescript

### ISSUE THREAD

**Issue by mdealiaga** [Prozi/detect-collisions#31]
In my project, I use this convention of creating entities:

```
this.collision = system.createCircle({ x: x, y: y }, r);
this.collision.mainObject = this
this.collision.objectType = 'player' / 'enemy' / 'bullet' / etc
```

This is helpful during the handle collision stage so I can do something like

```
handleCollision(collider, response) {
		switch (collider.objectType) {
			case 'bullet':
                                	this.takeBulletDamage(collider.mainObject.projectileType, collider.multipliers, collider.mainObject.damage, collider.mainObject.effectsList, collider.mainObject.effectsDuration)
				break
			case 'spike':
				// code
				break
			case 'pickup':
				// code
				break
			case 'water':
				//code
				break
                        case undefined:
                                handleBodyOverlap(this.collision, response)
                      }
}
```

With Typescript, this naturally causes the compiler to complain. I'm curious what design pattern would be ideal here to obtain this behaviour with Typescript.

I noticed on tank there is  `if (a.type === "Circle" || a === this.player) {`
But, this only checks if something is a specific shape, or compares to another collision object (rather than a group).

I'm guessing I'll have to extend the types, but does this mean I need to branch off my own version of the package? Alternatively, do you use a different design pattern that works better for this package?

**Comment by Prozi** [comment]
hello

> I'm guessing I'll have to extend the types

yes propably extend the type in handleCollision function

like 

```
import { Body, Response } from 'detect-collisions';

handleCollision(collider: Body & { objectType: string }, response: Response) {
```

but I am missing some information here: 
what kind of errors/complaints are you getting from compiler and where

> but does this mean I need to branch off my own version of the package?

no surely you dont have to :-) I am confident we will work something out here

> Alternatively, do you use a different design pattern that works better for this package?

what you're doint seems totally ok

**Comment by Prozi** [comment]
one question wouldnt you rather just assume the collider always has mainObject so

you can change to 

```
this.objectType = 'player';
this.body = system.createCircle({ x: x, y: y }, r);
this.body.mainObject = this;
```

		switch (collider.mainObject.objectType) {
```

**Comment by mdealiaga** [comment]
Thank you @Prozi, fairly new to TS so I wasn't sure what to do, but this led me down the right path.

I had to make this additional change to your example, because there was still an error when I needed to access properties of mainObject, since Player, Enemy, Bullet, etc  all have different properties inside it, but this change fixed that:

```
type BodyOptions = {
	objectType: 'bullet',
	mainObject: Bullet,
} | {
	objectType: 'player',
	mainObject: Player,
} | {
	objectType: 'trap',
	mainObject: undefined
} | {
    objectType: 'interestManagement',
    mainObject: Player
} | { 
    objectType: 'enemy', 
    mainObject: Enemy 
}
export type MyBody = Body & BodyOptions;
```
[I made a small sandbox of the fix too](https://www.typescriptlang.org/play?#code/C4TwDgpgBACgFiAzgSwMaIEIHsAmIoC8UA3gFACQAHgFxQB2ArgLYBGEATgDQUi2Osdu5dgEMcyBoj7M27UgF9SpUJFgAbESA6ESFSRzoimEWomDtkdAOZCwWS8Cn0ZHCnAgi1wONIFcKwCIA1hAAIkYiViZQABQ4EVG+sgCUhAB8UABu9jhCcCJ0OGoQAMJYamrIKFh0tDGo5ZU4HLTYeKkEGdnIOArK4NAYDBUQwDpk5IiQEDhJruTxTJHR-LJ9KtAAKqJg4wE7AIKowMiZIsAztCxY5R50ff2qbfhE8EhomLj4AGS65FgsABWEGOmwGtAA5CxhsVgBChEtLAB5IEg4CtGGjbjyKAAHz+AOBoPBUAhYA0WnY8IoiLoKKJ6PUmkECjxBNRxMgkPMIjA1PItPpaNo215DwadDMUHJzPYAEY9uR9OxDMZIdcWPy7A4nABWAAMeQ8Xh8UDl+sNAWCYQSEDitrm7FSE3I3iqADp3J5vFAALRERbLCjyPIFIqlRpVZA1eqR5rsVpfZ0USYAd2QwFQcFiDQqPQ47sJaLBkGT5HLqBEiGgUMxcOoKfLbsQ7sCIXCSyisbz8fdgo5wHdgaiyUb5BY7A8QUblerpJ5fIb5fLyAAZjm4wX+wzW4djqdzjMy8vXXAPW2bZ27QbRyfFCeJ1OZ1XoAxChBV5ZLmOAPQ-qD5IUxRQFgq6rtWwBjo+wQpveiiKKQECUHY7BjMQ8hAA)

Regarding

> one question wouldnt you rather just assume the collider always has mainObject so

The reason I have not done this is because

1. Some of my objects have two physics bodies. For example Player has a bigger "Interest Management" circle to see what to send to the player's screen in my multiplayer game (I thought this would be more efficient than keeping a separate algorithm for what to send to players).
Therefore, Player would need to have both ``objectType == 'player'`` and ``objectType == 'interestManagement`` which would not make sense.

2. Other objects such as ``water`` don't have any additional information so it would just be ``mainObject = {objectType: 'water'}``. In this case, this might still be better to having two extra properties.

Thanks again!

**Comment by Prozi** [comment]
> Thank you @Prozi, fairly new to TS so I wasn't sure what to do, but this led me down the right path.
> 
> I had to make this additional change to your example, because there was still an error when I needed to access properties of mainObject, since Player, Enemy, Bullet, etc all have different properties inside it, but this change fixed that:
> 
> ```
> type BodyOptions = {
> 	objectType: 'bullet',
> 	mainObject: Bullet,
> } | {
> 	objectType: 'player',
> 	mainObject: Player,
> } | {
> 	objectType: 'trap',
> 	mainObject: undefined
> } | {
>     objectType: 'interestManagement',
>     mainObject: Player
> } | { 
>     objectType: 'enemy', 
>     mainObject: Enemy 
> }
> export type MyBody = Body & BodyOptions;
> ```

This looks sweet.

Can we close the issue?

Best regards
