### ISSUE TITLE
forEach in checkAll() and asynchronous operations in callback

### ISSUE THREAD

**Issue by trekze** [Prozi/detect-collisions#40]
We've upgraded from a much older version version of detect-collisions, and it's mostly working as intended, aside for some rare race condition-like symptoms. Our handlecollisions callback has async calls in it at times. Wondering if this might be caused by checkAll() using foreach internally instead of for...of. Is it possible this might cause several of the callbacks to be called in parralel?

Thanks for your help. Amazing library.

**Comment by Prozi** [comment]
> Is it possible this might cause several of the callbacks to be called in parralel?

as far as I know javascript can't really execute something in paralel since its single threaded :)

I am not sure I know what you mean, can you provide me with some minimal sample of code?
