### ISSUE TITLE
Moving concave polygons doesn't work

### ISSUE THREAD

**Issue by jmankopf** [Prozi/detect-collisions#42]
The position of the decomposed convex polygons are only set in the updateConvexPolygons() method, but not when updating the position of the body.

#43

**Comment by Prozi** [comment]
merged your MR, rebuilt, and published new version as v6.6.8 with it

thank you

**Comment by jmankopf** [comment]
Thank you for your work!

**Comment by Prozi** [comment]
no problem thanks for contributing!

closing as resolved
