### ISSUE TITLE
How to use isTrigger?

### ISSUE THREAD

**Issue by keenfoong** [Prozi/detect-collisions#44]
Hello, I'm using the detect-collisions library and it is working great so far thanks.
I'm a little unsure though on how to use the onTrigger functionality. When I run `checkAll` the trigger is still there with all the collisions calculated:

```typescript
physics.checkAll((resp) => {
     // resp has all the overlap data
})
```
I'm attempting to use isTrigger to minimize impact on performance. For instance if I have hundreds of bullets, I don't need to know the exact overlap, just that it is within its bounding box. 

I was thinking of maybe using `getPotentials()` as well without using `physics.checkCollision()` to save on performance. Will the bodies from `getPotentials()` tell me if an object is close enough to another?

**Comment by keenfoong** [comment]
Ok thanks!

**Comment by Prozi** [comment]
@keenfoong closing this as I guess you don't have any more questions

**Comment by keenfoong** [comment]
Thanks, things are working well on my end here.
