### ISSUE TITLE
Line: Rounding error on maxY

### ISSUE THREAD

**Issue by tmanninger** [Prozi/detect-collisions#47]
I create the following line:
```
      let line = new Line(
        { x: 600.51305, y: 69.7 },
        { x: 600.51305, y: 229.052 }
      );
```
After system.update(), the min/max auf the body have the following values:
```
minX: 600.51305
minY: 69.7
maxX: 600.51305
maxY: 229.05199999999996
```

Why is maxY rounded to `229.05199999999996`?

Now, when i check, if on position `{ x: 600.51305, y: 229.052 }` is a collision, the check returns false.

See example (see console output):
https://codesandbox.io/s/proud-snowflake-04p5nh?file=/src/App.tsx:352-459

**Comment by tmanninger** [comment]
My current dirty lifehack:

Instead auf using system.update():
```
        for (let body of this._collisionSystem.all()) {
            if (body instanceof Line) {
                body.minX = body.points[0].x
                body.minY = body.points[0].y
                body.maxX = body.points[1].x
                body.maxY = body.points[1].y
            }
            else {
                this._collisionSystem.updateBody(body)
            }
        }
```

**Comment by Prozi** [comment]
the reason @tmanninger is that in javascript `229.052 - 69.7 + 69.7 === 229.05199999999996` :smiling_face_with_tear: 

you implementation ignores padding and line position
- Line has pos (x, y) and 2 points (start, end)
- point[0] = { x: 0, y: 0 };
see https://github.com/Prozi/detect-collisions/blob/master/src/bodies/line.ts

**Comment by tmanninger** [comment]
@Prozi other question (i know this is not issue related):
Is there a way to update a Line object without adding it to the system object?

i will create a new Line object, update the attributes, check if there is a collision with the Line object. After this, the line object is not longer needed.
My current way:
1.) Create Line object
2.) Add it to system
3.) call system.update(line)
4.) Check collision with another object.
5.) Delete line from system.

**Comment by Prozi** [comment]
> @Prozi other question (i know this is not issue related): Is there a way to update a Line object without adding it to the system object?
> 
> i will create a new Line object, update the attributes, check if there is a collision with the Line object. After this, the line object is not longer needed. My current way: 1.) Create Line object 2.) Add it to system 3.) call system.update(line) 4.) Check collision with another object. 5.) Delete line from system.

you can either

skip step 3 (adding to system is same as updating body)
// this is the way to go

or

you can just try to do
1) Create Line
2) system.all().filter((body) => this.checkCollision(line, body))

but I dont recommend this unless you have a very small number of bodies as BVH is always faster for idk >100 bodies?

**Comment by Prozi** [comment]
closing as [wont-fix] (the issue described in https://github.com/Prozi/detect-collisions/issues/47#issuecomment-1377062769 )
