### ISSUE TITLE
Docs: improvement

### ISSUE THREAD

**Issue by Mero-Plaform** [Prozi/detect-collisions#49]
I tried to test collision for my pet project, where shapes gonna use rotation and only after half a day of trying to find another collision libriry, I discovered, that **angles** are using in **radians**.

```
// wrong 45deg rotation
new Box({ x: 100, y: 100 }, 100, 100, { angle: 45 });

// correct 45deg rotation
new Box({ x: 100, y: 100 }, 100, 100, { angle: 0.785398 });
```

Please, provide more params details, I like your lib, I rly do, but it should be more friendly. I think many ppl have abandoned it after failing to figure out how to use it.

**Comment by Prozi** [comment]
@vadimTestPlatform thank you for opening an issue

of course, I will add this to docs and provide better explanation

I will also add a conversion functions deg2rad and rad2deg for easier use

are there any other improvements I can do?

**Comment by Prozi** [comment]
added those 3 inside readme and api docs since 6.8.0

looking forward to improving further

**Comment by vadimTestPlatform** [comment]
Body property "isStatic", no description highlights the point of using it

**Comment by vadimTestPlatform** [comment]
Highlight "Deprecated" paragraph

**Comment by vadimTestPlatform** [comment]
unclear "isTrigger" property description, "as ghost" as I understood - it doen't trigger collision on check, but it does

**Comment by Prozi** [comment]
@vadimTestPlatform what do you think about https://github.com/Prozi/detect-collisions/blob/dev/README.md I added some improvements you mentioned and then some more

**Comment by Mero-Plaform** [comment]
@Prozi looks good, just few moments:

- line 222, "although this is very not recommended as the BVH (rbush) broad-phase-search with bounding boxes makes the collision checking a lot more efficient."
   - "although" -> "Although"
   - I think phrases "very not recommended" & "a lot more efficient" should be somehow highlighted to emphasize the importance of the possible performance issues.
   
Although I want to recommend you change Benchmark table output: "index" column is little confusing(it's superfluous) and "value" column, maybe shoud be renamed to "fps" or I event can't understand, what "value" is meaning there )

**Comment by Mero-Plaform** [comment]
system method "checkCollision" has unclear param "response'

need to provide the meaning of its use

and I recommend to rename params from "body" & "wall" -> "body1" & body2", cause the "wall" param could be represented with circle etc, that's a little bit confusing

**Comment by Codezilluh** [comment]
some contribution instructions in the README would also be nice :)

**Comment by Prozi** [comment]
thanks for input.

about renaming wall to body I did it and will ship with next minimal update

about console.table indexes https://developer.mozilla.org/en-US/docs/Web/API/Console/table so I guess I'd have to switch to some different logs for that

about improvements to english in readme thanks will do them

will add some contributions sections too###

**Comment by Mero-Plaform** [comment]
improve system "draw" & "drawBVH" methods description

like here: https://prozi.github.io/detect-collisions/classes/Box.html#draw.draw-1

also can't understand the differences between them

maybe should provide more info in readme 

at "The BVH can also be drawn to help test" section

**Comment by Prozi** [comment]
hello @Mero-Plaform 

since version v8.0.0 the documentation has been extended on this subject,
moreover all the bodies have gotten their own independent drawBVH functions

please see

**Comment by Prozi** [comment]
closing until more changes to docs requested, thanks
