### ISSUE TITLE
System detects collision between two polygons, but does not return overlap values 

### ISSUE THREAD

**Issue by wetterben** [Prozi/detect-collisions#5]
Hey @Prozi, 

thanks for this cool library. It saves me a lot of work! 

I use this library for a 2d browser game, where you can only see the game directly from above. So far everything went great: The player couldn't run out of the world, couldn't run into objects and disappear bullets when they fly against an object or hit a player. 

So far I've only tested collisions where a circle collides with a polygon or another circle. But since I have added vehicles now, I also test whether a polygon (the vehicle) collides with a circle or a polygon. And that's the problem. When the vehicle enters an object, the library reports a collision, but all overlap values remain at zero. This happens especially when I test if the vehicle collides with a polygon. With a circle, the values change briefly so that the vehicle glitches through the object. And strangely enough, everything works perfectly with the world borders made of lines. 

I've tried everything and I'm absolutely desperate right now. I looked very closely at the tank demo, which is actually similar, and actually did everything like that. 

That's why I'm asking you here if you have an idea why that might be or if someone has had the same problem here before. 

Thank you in advance!

**Comment by Pii2** [comment]
did you find a solution ? 
I'm struggling with the same Problem ... All Overlap values are 0 by testing a collision between tow polygons (rectangles).

**Comment by b3ngg** [comment]
Sorry, I finished my mentioned project two years ago. Looking into the code, it looks like I ended up using a different library for it. Maybe that one will help you too. Should do in about the same thing: https://github.com/TuurDutoit/crash

**Comment by Pii2** [comment]
I'll look into it, thanks for the reply! :)

**Comment by Prozi** [comment]
hello i love your lib. i rewrote detect-collisions to also use rbush and sat since version 3

greetings! and thanks for inspiration

**Comment by b3ngg** [comment]
Awesome! Looks great, I will definitely use it in future projects!
