### ISSUE TITLE
Fix: isCentered

### ISSUE THREAD

**Issue by Mero-Plaform** [Prozi/detect-collisions#58]
After creation new body with option "isCentered", it appears at wrong position

**like it wasn't centered**

_(Bigger box has "isCentered" option, smaller - doesn't)_

![1](https://user-images.githubusercontent.com/31737393/220386086-c05bc228-1461-4895-9e00-336b39823c59.png)

after updating positions manualy, body with "isCentered" option

is using right coords

_(I setted same coords for setPosition as in creation params)_

![2](https://user-images.githubusercontent.com/31737393/220386876-38f6a9a4-bb29-46bf-b5f5-607c2ef1b3a6.png)

In my example squares got same coords twice, but centered did change it's position

It's weird behavior, I think It should use right position from the begining(creation moment)

My code:

```
/* --------------------------------- canvas --------------------------------- */

const canvas = document.querySelector('canvas')!;
const context = canvas.getContext("2d")!;

canvas.height = 700;
canvas.width = 700;

context.strokeStyle = "#aa2299";
context.fillStyle = "#aa3388";

/* --------------------------------- system --------------------------------- */

const system = new System();
const box1 = new Box({ x: 50, y: 50 }, 100, 100);
const box2 = new Box({ x: 50, y: 50 }, 50, 50, { isCentered: true });

system.insert(box1);
system.insert(box2);

/* --------------------------------- launch --------------------------------- */

// setting same pos as in creation params
// box1.setPosition(50, 50);
// box2.setPosition(50, 50);

system.draw(context);
context.stroke();
```

**Comment by Prozi** [comment]
hello @Mero-Plaform this is not a bug.

try rotating both boxes

**Comment by Prozi** [comment]
the isCentered is changing the points itself so the anchor for rotation is in the center of polygon

**Comment by Prozi** [comment]
see https://prozi.github.io/detect-collisions/interfaces/BodyProps.html#isCentered

**Comment by Mero-Plaform** [comment]
rotation works fine, position at creation moment - not

I will try again, here is simple box(h:50, w:50), created at x:50, y:50:

Code:
```
new Box({ x: 50, y: 50 }, 50, 50)
```
View:
![1](https://user-images.githubusercontent.com/31737393/220616064-076d22aa-a0b1-4d22-8573-f8d9f43918b0.png)

It's moving anchor is at left top corner and everything works just fine

If I move it to x:50, y:50, it's not changing position(visually), it's already there:

Code: 
```
box.setPosition(50, 50);
```
View:
![1](https://user-images.githubusercontent.com/31737393/220616681-805453cf-1870-496a-9c08-6c7e12e2873f.png)

**But**

If I do the same, using "isCentered" box initial position is wrong:

Code:
```
new Box({ x: 50, y: 50 }, 50, 50, { isCentered: true })
```
View:
![1](https://user-images.githubusercontent.com/31737393/220616064-076d22aa-a0b1-4d22-8573-f8d9f43918b0.png)

The real moving anchor of the box is now at it's center and it we can see it 

after moving it to same position, where we create it:

Code: 
```
box.setPosition(50, 50);
```
View: 

![2](https://user-images.githubusercontent.com/31737393/220617426-2eeb8483-6ec8-4187-9d46-cf7902f736a3.png)

if I move it to x:100, y:100 we can clearly see, moving anchor is at it's center:

Code: 
```
box.setPosition(100, 100);
```
View: 
![3](https://user-images.githubusercontent.com/31737393/220618580-9bc81749-9d48-41be-b82b-3210bb3e1544.png)

Conclusion:
1. "isCneterd" is changing box anchor not just for rotation but and moving
2. box with "isCneterd" option is creating at wrong position, the right position will be used, after first position update by "setPosition"

I think problem №2 appears, because "setPosition" is using center anchor for calculating new points, while creation logic is not

Hope, I provide good explanation

**Comment by Mero-Plaform** [comment]
@Prozi thx for your answer

Most elements will change their position in some case, like on collision handling 

Better they won't teleport after first "setPosition"

Or we will need as a hack to use "setPosition" on all elements after creation to set them to their real poses

**Comment by Prozi** [comment]
hello @Mero-Plaform I've finally decided to address this.

since version v8.0.0 the centering does not alter position of body

please try

**Comment by Mero-Plaform** [comment]
hello @Prozi 

yes, now body coords works as it predicted from at creation moment
