### ISSUE TITLE
getPotentials() alternative to do BVH without SAT

### ISSUE THREAD

**Issue by mdealiaga** [Prozi/detect-collisions#59]
I am updating and noticed getPotentials was deprecated.

However in my project I do not always need to check SAT when detecting collisions. This is mainly for doing viewport culling.
Players have a box around them the size of their screen, and I include any object that collides with it, but there is no need to check for SAT, including slightly more objects doesn't matter.

My code is something like this
```
const potentials = system.getPotentials(this.collision)
for (let i = 0; i < potentials.length; i++) {
	const object = potentials[i]
	if (object.objectType == 'interestManagement') {
		object.mainObject.interestManagementPotentials.push(this.collision)
	} else {
		if (system.checkCollision(this.collision, object)) {
			this.handleCollision(object, system)
		}
	}
}
```

> reasoning behind this is that inside this requires a filter to check is a potential returned body not being itself. so when you get 1000 potentials you will iterate over that twice

Is this saying that my loops are half as efficient compared to checkAll?

Thank you for your time

**Comment by Prozi** [comment]
> Is this saying that my loops are half as efficient compared to checkAll?

Sorry for late reply @mdealiaga 

Using getPotentials() is more like 1% less efficient (but in reality very hard to estimate but not 50% for sure) because of one conditional and one iteration but no additional computation there - if that makes sense

feel free to ask any more questions

**Comment by Prozi** [comment]
but if you're not using `system.checkAll()` at all AND you have more than one moving body - then you may be loosing more than that 1% and I strongly suggest to refactor your code to use `system.checkAll()`

**Comment by mdealiaga** [comment]
I have many moving bodies, it's an .io game top down shooter so it could be like 30 active entities + 30 bullets per tick (so 60 moving bodies getPotentials()) called per tick)
Ideally I would handle more but my servers are cpu-capped so I would love to improve efficiency, do you think this would be a massive improvement?

Using system.checkall would mean I either have to change how I do interest management to see what data to send to players, or do SAT a lot when not needed, but if it's a massive improvement I would refactor it.

**Comment by mdealiaga** [comment]
> but if you're not using `system.checkAll()` at all AND you have more than one moving body - then you may be loosing more than that 1% and I strongly suggest to refactor your code to use `system.checkAll()`

I checked the code and I think I see what you are saying, it uses this filter here unnecesarily 60x` **filter**(this.search(body), (candidate: Body) => candidate !== body);`

Is that what you mean (which I can see can get expensive) or are there also other optimisations I am not realising? Does it also stop searching after getting 1 collision hit while the other doesn't?

I have bodies where I just need to access the BVH this.search results, so I think I would need something like 

```
    checkOne(body, callback, response = this.response) {
        // no need to check static body collision
        if (body.isStatic) {
            return false;
        }

        const bodies = this.search(body);
        const checkCollision = (candidate) => {
            if (candidate !== body &&
                 (**this.skipNarrowPhase ||**
                this.checkCollision(body, candidate, response))
) {
                return callback(response);
            }
        };
        return (0, optimized_1.some)(bodies, checkCollision);
```

However, I can see that may be a niche use-case, so I'm not sure if you would think it's worth having it in the library. If so maybe I could use 'patch-package' or something to add that in for my project while still using checkAll

**Comment by Prozi** [comment]
1. without changing any code inside the library
2. and without changing your app/game logic

I am positive it's worth to refactor from getPotentials to at least checkOne

this way you can do something like

```
// I bet you propably have something like this already
const collidingBodies = [...bullets, ...players];

// then you just need to do
collidingBodies.forEach(body => {
  system.checkOne(body, collisionHandler)
});
```

where
```
const collisionHandler = ({ a, b, overlapV }) => {
  // your collision logic here
  console.log(a, b, overlapV);
};
```

and as far as is checkOne() or checkAll() better in your specific case,

it's up to specifics of your game, but you may be able to test that:

if you do the above, just save changes and commit.

then try such a refactor (on a separate branch)

1. add to your non moving bodies isStatic flag = true (you can do it in BodyOptions in creation time or in runtime)
2. replace this
```
collidingBodies.forEach(body => {
  system.checkOne(body, collisionHandler)
});
```

with this

```
system.checkAll(collisionHandler);
```

and then compare the results.

it is possible simply checkOne is better than checkAll in your case
but surely you don't need getPotentials

greetings

**Comment by Prozi** [comment]
> > but if you're not using `system.checkAll()` at all AND you have more than one moving body - then you may be loosing more than that 1% and I strongly suggest to refactor your code to use `system.checkAll()`
> 
> I checked the code and I think I see what you are saying, it uses this filter here unnecesarily 60x` **filter**(this.search(body), (candidate: Body) => candidate !== body);`

yes! and that is 60x filter on **all** bodies so I guess that adds up a bit

> Is that what you mean (which I can see can get expensive) or are there also other optimisations I am not realising? Does it also stop searching after getting 1 collision hit while the other doesn't?

if you return true in `collisionHandler` it stops after first collision

**Comment by Prozi** [comment]
closing as nothing else to explain here and no more questions,

thanks
