### ISSUE TITLE
Check Poylgon before insert?

### ISSUE THREAD

**Issue by Maeggi** [Prozi/detect-collisions#6]
Hi Prozi,
can Check a polygon of "Collision" and "other polygons nearby", **before insert it**?

**Comment by Prozi** [comment]
`return collisionDetection.update()` after insert if it collides or manually

something like:
```
      const potentials = obj.collider.potentials()
      const result = this.getResult()
      for (const wall of potentials) {
        if (obj.collider.collides(wall, result)) {
          if (!collided) {
            collided = done(obj, wall, result)
          } else {
            done(obj, wall, result)
          }
        }
      }
```

@Maeggi

**Comment by Maeggi** [comment]
Thank You @Prozi

**Comment by Prozi** [comment]
No problemo

Added to documentation: https://www.npmjs.com/package/detect-collisions/v/2.5.1#anchor-step-7
