### ISSUE TITLE
Bug: Storing Response reference instead of new instance in system.checkAll and system.checkOne methods

### ISSUE THREAD

**Issue by HoangTran0410** [Prozi/detect-collisions#62]
When I use **system.checkAll / system.checkOne**, the response instance is passed down the tree. So when I want to store a list of responses for later use, it's just a reference to the same response, which is incorrect.

Code example:
```javascript
let result = [];
this.system.checkOne(body,(response) => {
    result.push(response) // save for later use
});
console.log(result) // <-- all responses are just a reference to the same instance (system.response)
```

I have tried different approaches. But still have similar issues:
```javascript
let result = [];
this.system.checkOne(body,({...response}) => {
    result.push(response)
});
console.log(result) // <-- different instance, but still have a reference to the same overlapV, overlapN object, etc.
```

```javascript
let result = [];
this.system.checkOne(body,(response) => {
    result.push(response)
}, 
new Response() // insert new instance
);
console.log(result) // <-- different instance, but still have a reference to the same overlapV, overlapN object, etc.
```

I think we should create a new instance for each **checkCollision/checkAll/checkOne** call to prevent this issue.

This issue will cause a bug when separating a circle into multiple polygons at once frame. Because the overlapV is not correct.

**Comment by HoangTran0410** [comment]
I suggest adding a new function to the library that clones a Response object. It would be great if the function could support cloning objects like this:

```javascript
function cloneResponse(response: Response) {
  return {
    ...response,
    overlapV: response.overlapV.clone(),
    overlapN: response.overlapN.clone(),
    // ... any other object
  };
}
```

**Comment by HoangTran0410** [comment]
I hope you can fix this. It took me 6 hours to debug and figure out why my collision separation is incorrect. 😒😢🥲

**Comment by alexvgjm** [comment]
I just ran into the same problem. I assumed out of habit that responses were simply immutable data objects.

Multiple methods receive an object of type Response, which by default uses a shared one, a member of a System instance which is cleared and filled on each check. A similar design decision has been made with overlaps, they are created and shared in multiple iterations within check methods. I am completely unaware of what led to this design decision, for no apparent benefit. It complicates persistence and state management in a devastating way.

I'd love to say that this is the only design issue you'll see, but sadly it isn't. Not only coming from detect-collisions, but also from its dependencies like SAT and RBush. It certainly discourages contributing with so many things to fix, sometimes being difficult to differentiate what we consider to be objectively correct from what is opinionated.

After so much negative talk, I think it's worth emphasizing that this is one of the best and simplest libraries focused solely on 2D detection. It's a good starting point for developing something more polished.

**Comment by Prozi** [comment]
nice!

thank you @HoangTran0410 for opening an issue and @alexvgjm for confirming

I'm planning to look into this and fix it this weekend

**Comment by Prozi** [comment]
well, this is actually more like a feature request than a bug but I did what you asked for:

please see https://github.com/Prozi/detect-collisions/releases/tag/v9.2.2

🙂
