### ISSUE TITLE
Feature request: for debug canvas draws, can we manipulate draw color by entity type

### ISSUE THREAD

**Issue by jyoung4242** [Prozi/detect-collisions#65]
![image](https://github.com/Prozi/detect-collisions/assets/62815737/094733d8-be10-4b53-b1c2-b10c1f5618f2)

each entity in my system has a color assigned to it, it would be 'neat' if i could manipulate the canvas strokestyle by entity...

just a though...

**Comment by Prozi** [comment]
> each entity in my system has a color assigned to it, it would be 'neat' if i could manipulate the canvas strokestyle by entity...
> 
> just a though...

hello sorry for late reply

if you something like:

```
class Character extends Box {
  draw(context: CanvasRenderingContext2D) {
    context.strokeStyle = '#ff0000';
    super.draw(context);
  }
}

class Obstacle extends Box {
  draw(context: CanvasRenderingContext2D) {
    context.strokeStyle = '#0000ff';
    super.draw(context);
  }
}
```

https://github.com/Prozi/detect-collisions/blob/master/src/bodies/polygon.ts#L273C1-L275C1

you should achieve what you need. this will override the draw class of those bodies and when you use them with system.draw(ctx) or body.draw(ctx) it will work like you desire

best regards, Jacek.

does this solve your request?

**Comment by Prozi** [comment]
```
```
class ColoredBox extends Box {
  draw(context: CanvasRenderingContext2D) {
    context.strokeStyle = this.color;
    super.draw(context);
  }
}
```

or something more generic like above

**Comment by jyoung4242** [comment]
I will check this out and let you know what i come up with... thanks for getting back to me

**Comment by Prozi** [comment]
> I will check this out and let you know what i come up with... thanks for getting back to me

I think it's fair to assume it works, closing
