### ISSUE TITLE
Trying to keep the object inside the walls with multiple collisions

### ISSUE THREAD

**Issue by whitespacecode** [Prozi/detect-collisions#69]
Not sure if it's a limitation or if i'm doing something wrong and need to do this another way. 
When i have 2 lines (concave shape) and the player is hitting 1 wall the overlap is pushing the player along that wall but neglects the other wall it's overlap ?
 
```
collisionSystem.checkAll((response: Response) => {
  if (response.a.isPlayer && response.b.isWall) {
    const { overlapV } = response;
    console.log(" overlapV:", overlapV)
    response.a.setPosition(
       response.a.x - overlapV.x,
       response.a.y - overlapV.y
    );
  }
});
```

i do get 2 collision response logs:
```
overlapV: Vector {x: -0, y: 21.264527400050127}
overlapV: Vector {x: -32.94248789963376, y: -16.47124394981688}
```

![image](https://github.com/Prozi/detect-collisions/assets/37139936/4e1e3f13-9534-4c95-ad38-c0562fc382c2)

https://github.com/Prozi/detect-collisions/assets/37139936/3bdf0cff-7d82-4043-bf47-0c05848d3c0a

**Comment by Prozi** [comment]
@whitespacecode in such complicated cases the solution is here

https://github.com/Prozi/detect-collisions/blob/master/src/system.spec.js#L9-L54

aggregate the offsets and then update position, and update AABB

**Comment by whitespacecode** [comment]
Thank you for the response. 
I already tried to sum of the overlap and then substract them all at once. (Would be great to add to the documentation).

What i think i happening:
![image](https://github.com/Prozi/detect-collisions/assets/37139936/937143c5-b93b-4923-b42e-be5505be19b5)

When i repeat the collision check 2 or 3 time the problem goes away
```
//Update player by mouse
playerBody.setPosition(mousePosition.x, mousePosition.y, false);

//Do this 3x
collisionSystem.checkAll(({ a, b, overlapV }) => {
  if (a.isPlayer && b.isWall) {
    playerBody.pos.x -= overlapV.x;
    playerBody.pos.y -= overlapV.y;
  }
});

//After all collision checks update body 
playerBody.updateBody()

//visually update debugcanvas
debugCollision.update();

//Update pixi object
this.x = playerBody.x;
this.y = playerBody.y;
```

The problem is still occurring and i will have to wait for the sweep implementation i think. You can close this question if you want.

**Comment by Prozi** [comment]
> Thank you for the response. I already tried to sum of the overlap and then substract them all at once. (Would be great to 
add to the documentation).

will most likely add to docs soon, and a function to auto do this in System, probably

> When i repeat the collision check 2 or 3 times the problem goes 'away'

yes. that makes sense but that is very highly suboptimal.

that happens because:

if there are bodies WALL_A and WALL_B and BULLET

and WALL_A and WALL_B collides with BULLET at (x, y) then if you negate only WALL_A collision

the result in this case is pushing the BULLET into collision with WALL_B

that is in short what happens here

> The problem is still occurring and i will have to wait for the sweep implementation i think. You can close this question if you want.

please don't close yet I would rather it stay open so I think about how to explain in docs better or improve implementation further

**Comment by Prozi** [comment]
@whitespacecode 

this is what you should use now:

https://prozi.github.io/detect-collisions/classes/System.html#separateBody

implementation:

https://github.com/Prozi/detect-collisions/blob/master/src/system.ts#L108

test:

https://github.com/Prozi/detect-collisions/blob/master/src/system.spec.js#L9

readme:

https://github.com/Prozi/detect-collisions?tab=readme-ov-file#step-7-body-separation

**Comment by Prozi** [comment]
please update to `v9.2.6`
