### ISSUE TITLE
Types: Could not find a declaration file for module 'poly-decomp'

### ISSUE THREAD

**Issue by ong-appxplore** [Prozi/detect-collisions#72]
Hi, I am currently using this module in my project. It is fine when running the project in development with `ts-node` but when I try to build it with the command `tsc`, I am getting a number of errors on failing to find the declaration file for `poly-decomp`

![image](https://github.com/Prozi/detect-collisions/assets/86945088/506eda1e-5dfe-4fe2-ba88-2a1e0e9f805a)

I have further check the lib `poly-decomp` and usage of `Polygon`, and `Point` are no longer there after version 0.1.1. 
I am not entirely sure if this a problem on my ts config or this lib. Can you please advise?

**Comment by Prozi** [comment]
@ong-appxplore please test your project with `detect-collisions@^9.5.0` I switched to `poly-decomp-es` and fixed export hopefuly this helps

**Comment by ong-appxplore** [comment]
@Prozi I just tried it and it can build fine now. Thank you so much!

**Comment by Prozi** [comment]
@ong-appxplore I'm happy to hear that!

thanks for using this library, creating a bug ticket and closing it!
