### ISSUE TITLE
Usage in browser?

### ISSUE THREAD

**Issue by rev111** [Prozi/detect-collisions#73]
Would like to do a little testing in the browser before trying it in a node backend.
My attempts are unsuccessful.
```
<script src="node_modules/detect-collisions/dist/system.js"></script>
<script src="detect.js"></script>
```
detect.js:
```
console.log("detect!");
const system = new System();
const box1 = system.createBox(100,100, 100, 100, {});
system.update();
```
console output:
```
system.js:2 Uncaught ReferenceError: exports is not defined
    at system.js:2:23
detect.js:3 detect!
detect.js:5 Uncaught ReferenceError: System is not defined
    at detect.js:5:16
```

I guess I have to webpack it first - how?

**Comment by Prozi** [comment]
also, you don't have to webpack

this is your example fixed:

```
Would like to do a little testing in the browser before trying it in a node backend.
My attempts are unsuccessful.

index.html
```HTML
<script src="detect.js" type="module"></script>
```

detect.js
```js
const { System } = require("detect-collisions");
console.log("detect!");
const system = new System();
const box1 = system.createBox(100,100, 100, 100, {});
system.update();
```

or replace first line with

```js
import { System } from "detect-collisions";
```

1. this is basic `javascript` 🙈  
2. in your `detect.js` you don't have any reference to `System`
3. don't import other files than `dist/index.js`
4. don't import in html files from `node_modules`

**Comment by rev111** [comment]
Dear Prozi, thanks for the extensive reply! 
I think I did not explain my question well: I'm talking about even more basic javascript in the browser - as in manually creating a html file with <script>-tags (or ES6 imports) and serve that html file to a browser instance - similar how the demo works with "http://localhost/detect-collisions-master/dist/demo/?stress". 
Is that possible? Judging from your answer, I think it is not:
`const { System } = require("detect-collisions"); `=> this is of course node js and can't work in the browser.
`import { System } from "detect-collisions"; `=> wouldn't work as well because detect-collisions is not defined:
`Uncaught TypeError: Failed to resolve module specifier "detect-collisions". Relative references must start with either "/", "./", or "../".`
I guess the reason this works on stackblitz is because it imports / transpiles / converts the node module dependencies.
Following your advice 3, I also tried 
`<script src="../detect-collisions-master/dist/index.js"></script>` which gives me the same `exports is not defined` error as above. Even if I try `<script>var exports = {};</script> `(from [here](https://stackoverflow.com/questions/43042889/typescript-referenceerror-exports-is-not-defined)) I get a require-Error (of course!).

I think there is a step between https://prozi.github.io/detect-collisions/#md:demos and the demo in dist/demo.js, which seems to run without any dependencies. Can I use the library in the browser, similarily to the demo?

**Comment by Prozi** [comment]
yes you can't use this package straight in the browser
you would have to use something like here
https://unpkg.com/browse/detect-collisions@9.2.3/dist/index.js
or here
https://cdn.jsdelivr.net/npm/detect-collisions@9.8.0/dist/index.min.js

best of luck

do you have a feature request? @rev111

**Comment by Prozi** [comment]
sorry @rev111 for misinformation, YOU CAN ACTUALLY USE THIS PACKAGE IN BROWSER

create `index.html` file and put there

```html
<script type="module">
  import { System } from "https://cdn.skypack.dev/detect-collisions";
  
  const physics = new System();
  
  console.log(physics.createCircle());
</script>
```

it will work in browser without webpack

**Comment by Prozi** [comment]
test here or wherever if you need [(https://code.pietal.dev/#/boilerplate/empty](https://code.pietal.dev/#/boilerplate/empty?pans=html,console) just paste in the HTML Pan and see Console Pan for result

**Comment by Prozi** [comment]
need to add this to readme, reopening until then

**Comment by Prozi** [comment]
added here https://code.pietal.dev/#/boilerplate/detect-collisions?pans=html,console
