### ISSUE TITLE
IE 11: Expected Identifier error

### ISSUE THREAD

**Issue by CorporateDog** [Prozi/detect-collisions#8]
Hi,

Under IE 11 (which, unfortunately, I need to support) I'm receiving the following error:

![image](https://user-images.githubusercontent.com/713236/83328328-36481b00-a250-11ea-8f82-9105f974e956.png)

Thanks,
Dave

**Comment by Prozi** [comment]
There was an error in version 2.5.1

Update version to 2.5.2 (this is latest in moment of writing)

and try to require lib as 
```
var Collisions = require('detect-collisions/es2105')
```

Please notify me did this solve your problem @CorporateDog

**Comment by CorporateDog** [comment]
> There was an error in version 2.5.1
> 
> Update version to 2.5.2 (this is latest in moment of writing)
> 
> and try to require lib as
> 
> ```
> var Collisions = require('detect-collisions/es2105')
> ```
> 
> Please notify me did this solve your problem @CorporateDog

Yes. This appears to have resolved the issue.

Thank you for your speedy response!

**Comment by Prozi** [comment]
Haha no problemo thanks for finding a bug and resolving the issue @CorporateDog
