### ISSUE TITLE
Moving Platforms

### ISSUE THREAD

**Issue by gregmax17** [Prozi/detect-collisions#83]
Anyway someone can provide a simple platformer with one moving platform?

**Comment by Prozi** [comment]
halfway pseudocode until I make something else

```ts
import { System, deg2rad } from 'detect-collisions';

const physics = new System();
const platformProps = { pos: { x: 100, y: 200 }, width: 100, height: 50, speed: 1 };
const platform = physics.createBox(platform.pos, platform.width, platformProps.height);

const canvas = document.createElement('canvas');
const context = canvas.getContext('2d');
document.body.appendElement(canvas);

setInterval(() => {
  const degrees =  (platform.x <= platformProps.minx) ? 0 : 180;
  platform.angle = deg2rad(degrees);
  platform.move(platform.speed);
  physics.draw(context);
}, 1000 / 60);
```

something like this (not tested) should give you a moving platform

allow me to also point you to my other library that may be useful for your case:
https://github.com/prozi/oneforall

in the case you'd use it you would
1. create Scene
2. create GameObject/Sprite/Animator/Container
3. create for above a body (PolygonBody)
4. bind to its update$ function like

```ts
gameObject.update$.pipe(takeUntil(gameObject.destroy$))
  .subscribe((deltaTime: number) => {
    // the example 1 interval content
  });
```

this would further ogranize your code and make sure when you destroy gameObject its body and children are destroyed properly too

have fun!

**Comment by gregmax17** [comment]
Thank you for the reply, but this doesn't solve my problem, probably because I didn't word my question correctly.

I have a player and a platform body, both using a Box. The player moves and jumps around collides with other Boxes in my scene. But when it comes to a moving platform the player does not move with the platform. How can I keep the player stuck/on to the platform so when the platform moves the player moves with it? And let's assume the platform is wide so the player can move on the platform while the platform is moving.

**Comment by Prozi** [comment]
@gregmax17 this assumes gravity = physics.

there are currently no plan to do it in library

you may do this fairly easy yourself

you should check if player collides with platform

if yes move player along x axis the same amount as platform

**Comment by Prozi** [comment]
since neither friction nor gravity is going to be added to the library because of philosophy that it should not be a full physics engine but a base for your own - closing sorry
