### ISSUE TITLE
Example of the raycast's third parameter please

### ISSUE THREAD

**Issue by gregmax17** [Prozi/detect-collisions#85]
Like the title says, can you doc an example using the raycast's third parameter please.

**Comment by Prozi** [comment]
https://prozi.github.io/detect-collisions/classes/System.html#raycast

basically it's a compare function in form of

```
(body, ray) => boolean
```

if you  return false in this function, the body should be skipped by raycast

**Comment by Prozi** [comment]
cc @gregmax17

**Comment by Prozi** [comment]
added to readme here https://github.com/Prozi/detect-collisions?tab=readme-ov-file#raycasting
