### ISSUE TITLE
Raycasting support

### ISSUE THREAD

**Issue by SINePrime** [Prozi/detect-collisions#9]
Raycasting would be an excellent addition and within scope of the package.

**Comment by Prozi** [comment]
what user api would you have in mind

it is quite easy to implement:

this is how I would do this: (not tested)
- create a temporary line (2 point polygon),
- add to system,
- check line's potentials using BVH,
- iterate over potentials them to check exact collisions,
- add collisions to array,
- select closest point to start of array,
- remove temporary line from system.

regards

**Comment by Prozi** [comment]
@SINePrime what would you expect from such Raycasting api ?

what example function names / functionalities would you want to have ?

**Comment by Prozi** [comment]
I've decided to keep it simple and went with

`system.raycast(start: Vector, end: Vector): { point: Vector; collider: TBody } | null`

and included it inside the tank test demo https://prozi.github.io/detect-collisions/demo/

**Comment by Prozi** [comment]
closing as working

available since v3.5.0
